insert into
springboot_country_tbl (id, countryname, countrycapital)
values
(1,'Tokyo','Japan'),
(2,'Jakarta','Indonesia'),
(3,'Manila','Philippines'),
(4,'Seoul','South Korea'),
(5,'Mexico City','Mexico'),
(6,'Cairo','Egypt'),
(7,'Beijing','China'),
(8,'Moscow','Russia'),
(9,'Bangkok','Thailand'),
(10,'Dhaka','Bangladesh'),
(11,'Buenos Aires','Argentina'),
(12,'Kinshasa','Congo (Kinshasa)'),
(13,'Tehran','Iran'),
(14,'London','United Kingdom'),
(15,'Paris','France'),
(16,'Lima','Peru'),
(17,'Luanda','Angola'),
(18,'Kuala Lumpur','Malaysia'),
(19,'Hanoi','Vietnam'),
(20,'Bogotá','Colombia'),
(21,'Dar es Salaam','Tanzania'),
(22,'Hong Kong','Hong Kong'),
(23,'Santiago','Chile'),
(24,'Riyadh','Saudi Arabia'),
(25,'Baghdad','Iraq'),
(26,'Khartoum','Sudan'),
(27,'Madrid','Spain'),
(28,'Nairobi','Kenya'),
(29,'Rangoon','Myanmar'),
(30,'Washington','United States'),
(31,'Singapore','Singapore'),
(32,'Abidjan','Cote dIvoire'),
(33,'Kabul','Afghanistan'),
(34,'Amman','Jordan'),
(35,'Berlin','Germany'),
(36,'Algiers','Algeria'),
(37,'Addis Ababa','Ethiopia'),
(38,'Brasília','Brazil'),
(39,'Kuwait City','Kuwait'),
(40,'Kyiv','Ukraine'),
(41,'Sanaa','Yemen'),
(42,'Guatemala City','Guatemala'),
(43,'Rome','Italy'),
(44,'La Paz','Bolivia'),
(45,'Pyongyang','North Korea'),
(46,'Antananarivo','Madagascar'),
(47,'Santo Domingo','Dominican Republic'),
(48,'Tashkent','Uzbekistan'),
(49,'Ouagadougou','Burkina Faso'),
(50,'Yaoundé','Cameroon'),
(51,'Accra','Ghana'),
(52,'Baku','Azerbaijan'),
(53,'Harare','Zimbabwe'),
(54,'Havana','Cuba'),
(55,'Phnom Penh','Cambodia'),
(56,'Mogadishu','Somalia'),
(57,'Bamako','Mali'),
(58,'Quito','Ecuador'),
(59,'Minsk','Belarus'),
(60,'Caracas','Venezuela'),
(61,'Vienna','Austria'),
(62,'Bucharest','Romania'),
(63,'Brazzaville','Congo (Brazzaville)'),
(64,'Warsaw','Poland'),
(65,'Damascus','Syria'),
(66,'Brussels','Belgium'),
(67,'Lusaka','Zambia'),
(68,'Budapest','Hungary'),
(69,'Conakry','Guinea'),
(70,'Kampala','Uganda'),
(71,'Abu Dhabi','United Arab Emirates'),
(72,'Muscat','Oman'),
(73,'Ulaanbaatar','Mongolia'),
(74,'Belgrade','Serbia'),
(75,'Prague','Czechia'),
(76,'Montevideo','Uruguay'),
(77,'Sofia','Bulgaria'),
(78,'Abuja','Nigeria'),
(79,'Maputo','Mozambique'),
(80,'Doha','Qatar'),
(81,'Dakar','Senegal'),
(82,'Nay Pyi Taw','Myanmar'),
(83,'Kigali','Rwanda'),
(84,'Tripoli','Libya'),
(85,'Tegucigalpa','Honduras'),
(86,'Tbilisi','Georgia'),
(87,'N’Djamena','Chad'),
(88,'Copenhagen','Denmark'),
(89,'Yerevan','Armenia'),
(90,'Nur-Sultan','Kazakhstan'),
(91,'Nouakchott','Mauritania'),
(92,'Bishkek','Kyrgyzstan'),
(93,'Tunis','Tunisia'),
(94,'Kathmandu','Nepal'),
(95,'Niamey','Niger'),
(96,'Managua','Nicaragua'),
(97,'Monrovia','Liberia'),
(98,'Port-au-Prince','Haiti'),
(99,'Islamabad','Pakistan'),
(100,'Ottawa','Canada'),
(101,'Stockholm','Sweden'),
(102,'Asmara','Eritrea'),
(103,'Freetown','Sierra Leone'),
(104,'Vientiane','Laos'),
(105,'Jerusalem','Israel'),
(106,'Bangui','Central African Republic'),
(107,'Panama City','Panama'),
(108,'Amsterdam','Netherlands'),
(109,'Lomé','Togo'),
(110,'Libreville','Gabon'),
(111,'Zagreb','Croatia'),
(112,'Dushanbe','Tajikistan'),
(113,'Lilongwe','Malawi'),
(114,'Cotonou','Benin'),
(115,'Colombo','Sri Lanka'),
(116,'Pretoria','South Africa'),
(117,'Oslo','Norway'),
(118,'Athens','Greece'),
(119,'Bujumbura','Burundi'),
(120,'Helsinki','Finland'),
(121,'Skopje','Macedonia'),
(122,'Chisinau','Moldova'),
(123,'Riga','Latvia'),
(124,'Kingston','Jamaica'),
(125,'Rabat','Morocco'),
(126,'Vilnius','Lithuania'),
(127,'San Salvador','El Salvador'),
(128,'Djibouti','Djibouti'),
(129,'Dublin','Ireland'),
(130,'The Hague','Netherlands'),
(131,'Asunción','Paraguay'),
(132,'Lisbon','Portugal'),
(133,'Bratislava','Slovakia'),
(134,'Tallinn','Estonia'),
(135,'Beirut','Lebanon'),
(136,'Cape Town','South Africa'),
(137,'Tirana','Albania'),
(138,'Wellington','New Zealand'),
(139,'Dodoma','Tanzania'),
(140,'Bissau','Guinea-Bissau'),
(141,'Canberra','Australia'),
(142,'Juba','South Sudan'),
(143,'Yamoussoukro','Cote dIvoire'),
(144,'Maseru','Lesotho'),
(145,'Nicosia','Cyprus'),
(146,'Windhoek','Namibia'),
(147,'Port Moresby','Papua New Guinea'),
(148,'Porto-Novo','Benin'),
(149,'Sucre','Bolivia'),
(150,'San José','Costa Rica'),
(151,'Ljubljana','Slovenia'),
(152,'Sarajevo','Bosnia And Herzegovina'),
(153,'Nassau','The Bahamas'),
(154,'Bloemfontein','South Africa'),
(155,'Fort-de-France','Martinique'),
(156,'New Delhi','India'),
(157,'Gaborone','Botswana'),
(158,'Paramaribo','Suriname'),
(159,'Dili','Timor-Leste'),
(160,'Male','Maldives'),
(161,'Georgetown','Guyana'),
(162,'Gibraltar','Gibraltar'),
(163,'Saint-Denis','Reunion'),
(164,'Malabo','Equatorial Guinea'),
(165,'Podgorica','Montenegro'),
(166,'Manama','Bahrain'),
(167,'Port Louis','Mauritius'),
(168,'Willemstad','Curaçao'),
(169,'Bern','Switzerland'),
(170,'Papeete','French Polynesia'),
(171,'Luxembourg','Luxembourg'),
(172,'Reykjavík','Iceland'),
(173,'Praia','Cabo Verde'),
(174,'Sri Jayewardenepura Kotte','Sri Lanka'),
(175,'Bridgetown','Barbados'),
(176,'Moroni','Comoros'),
(177,'Thimphu','Bhutan'),
(178,'Mbabane','Swaziland'),
(179,'Nouméa','New Caledonia'),
(180,'Honiara','Solomon Islands'),
(181,'Suva','Fiji'),
(182,'Ankara','Turkey'),
(183,'Castries','Saint Lucia'),
(184,'Cayenne','French Guiana'),
(185,'São Tomé','Sao Tome And Principe'),
(186,'Port-Vila','Vanuatu'),
(187,'Hamilton','Bermuda'),
(188,'Bandar Seri Begawan','Brunei'),
(189,'Monaco','Monaco'),
(190,'Gitega','Burundi'),
(191,'Port of Spain','Trinidad And Tobago'),
(192,'Apia','Samoa'),
(193,'Tarawa','Kiribati'),
(194,'Oranjestad','Aruba'),
(195,'Saint Helier','Jersey'),
(196,'Banjul','The Gambia'),
(197,'Mamoudzou','Mayotte'),
(198,'Majuro','Marshall Islands'),
(199,'Douglas','Isle Of Man'),
(200,'George Town','Cayman Islands'),
(201,'Victoria','Seychelles'),
(202,'Kingstown','Saint Vincent And The Grenadines'),
(203,'Andorra la Vella','Andorra'),
(204,'Saint John’s','Antigua And Barbuda'),
(205,'Nuku‘alofa','Tonga'),
(206,'Ashgabat','Turkmenistan'),
(207,'Nuuk','Greenland'),
(208,'Belmopan','Belize'),
(209,'Roseau','Dominica'),
(210,'Basseterre','Saint Kitts And Nevis'),
(211,'Tórshavn','Faroe Islands'),
(212,'Pago Pago','American Samoa'),
(213,'Valletta','Malta'),
(214,'Gaza','Gaza Strip'),
(215,'Grand Turk','Turks And Caicos Islands'),
(216,'Palikir','Federated States of Micronesia'),
(217,'Funafuti','Tuvalu'),
(218,'Vaduz','Liechtenstein'),
(219,'Lobamba','Swaziland'),
(220,'Avarua','Cook Islands'),
(221,'Saint George’s','Grenada'),
(222,'San Marino','San Marino'),
(223,'Al Quds','West Bank'),
(224,'Capitol Hill','Northern Mariana Islands'),
(225,'Stanley','Falkland Islands (Islas Malvinas)'),
(226,'Vatican City','Vatican City'),
(227,'Alofi','Niue'),
(228,'Basse-Terre','Guadeloupe'),
(229,'Hagåtña','Guam'),
(230,'Marigot','Saint Martin'),
(231,'Jamestown','Saint Helena, Ascension, And Tristan Da Cunha'),
(232,'Brades','Montserrat'),
(233,'Philipsburg','Sint Maarten'),
(234,'Yaren','Nauru'),
(235,'Pristina','Kosovo'),
(236,'Gustavia','Saint Barthelemy'),
(237,'Road Town','British Virgin Islands'),
(238,'Ngerulmud','Palau'),
(239,'Saint-Pierre','Saint Pierre And Miquelon'),
(240,'The Valley','Anguilla'),
(241,'Mata-Utu','Wallis And Futuna'),
(242,'Kingston','Norfolk Island'),
(243,'Longyearbyen','Svalbard'),
(244,'Tifariti','Morocco'),
(245,'Adamstown','Pitcairn Islands'),
(246,'Flying Fish Cove','Christmas Island'),
(247,'King Edward Point','South Georgia And South Sandwich Islands'),
(248,'San Juan','Puerto Rico'),
(249,'Charlotte Amalie','U.S. Virgin Islands');
