insert into
springboot_country_tbl (id, countryname, countrycapital)
values
(1,'Japan','Tokyo'),
(2,'Indonesia','Jakarta'),
(3,'Philippines','Manila'),
(4,'South Korea','Seoul'),
(5,'Mexico','Mexico City'),
(6,'Egypt','Cairo'),
(7,'China','Beijing'),
(8,'Russia','Moscow'),
(9,'Thailand','Bangkok'),
(10,'Bangladesh','Dhaka'),
(11,'Argentina','Buenos Aires'),
(12,'Congo (Kinshasa)','Kinshasa'),
(13,'Iran','Tehran'),
(14,'United Kingdom','London'),
(15,'France','Paris'),
(16,'Peru','Lima'),
(17,'Angola','Luanda'),
(18,'Malaysia','Kuala Lumpur'),
(19,'Vietnam','Hanoi'),
(20,'Colombia','Bogotá'),
(21,'Tanzania','Dar es Salaam'),
(22,'Hong Kong','Hong Kong'),
(23,'Chile','Santiago'),
(24,'Saudi Arabia','Riyadh'),
(25,'Iraq','Baghdad'),
(26,'Sudan','Khartoum'),
(27,'Spain','Madrid'),
(28,'Kenya','Nairobi'),
(29,'Myanmar','Rangoon'),
(30,'United States','Washington'),
(31,'Singapore','Singapore'),
(32,'Cote dIvoire','Abidjan'),
(33,'Afghanistan','Kabul'),
(34,'Jordan','Amman'),
(35,'Germany','Berlin'),
(36,'Algeria','Algiers'),
(37,'Ethiopia','Addis Ababa'),
(38,'Brazil','Brasília'),
(39,'Kuwait','Kuwait City'),
(40,'Ukraine','Kyiv'),
(41,'Yemen','Sanaa'),
(42,'Guatemala','Guatemala City'),
(43,'Italy','Rome'),
(44,'Bolivia','La Paz'),
(45,'North Korea','Pyongyang'),
(46,'Madagascar','Antananarivo'),
(47,'Dominican Republic','Santo Domingo'),
(48,'Uzbekistan','Tashkent'),
(49,'Burkina Faso','Ouagadougou'),
(50,'Cameroon','Yaoundé'),
(51,'Ghana','Accra'),
(52,'Azerbaijan','Baku'),
(53,'Zimbabwe','Harare'),
(54,'Cuba','Havana'),
(55,'Cambodia','Phnom Penh'),
(56,'Somalia','Mogadishu'),
(57,'Mali','Bamako'),
(58,'Ecuador','Quito'),
(59,'Belarus','Minsk'),
(60,'Venezuela','Caracas'),
(61,'Austria','Vienna'),
(62,'Romania','Bucharest'),
(63,'Congo (Brazzaville)','Brazzaville'),
(64,'Poland','Warsaw'),
(65,'Syria','Damascus'),
(66,'Belgium','Brussels'),
(67,'Zambia','Lusaka'),
(68,'Hungary','Budapest'),
(69,'Guinea','Conakry'),
(70,'Uganda','Kampala'),
(71,'United Arab Emirates','Abu Dhabi'),
(72,'Oman','Muscat'),
(73,'Mongolia','Ulaanbaatar'),
(74,'Serbia','Belgrade'),
(75,'Czechia','Prague'),
(76,'Uruguay','Montevideo'),
(77,'Bulgaria','Sofia'),
(78,'Nigeria','Abuja'),
(79,'Mozambique','Maputo'),
(80,'Qatar','Doha'),
(81,'Senegal','Dakar'),
(82,'Myanmar','Nay Pyi Taw'),
(83,'Rwanda','Kigali'),
(84,'Libya','Tripoli'),
(85,'Honduras','Tegucigalpa'),
(86,'Georgia','Tbilisi'),
(87,'Chad','N’Djamena'),
(88,'Denmark','Copenhagen'),
(89,'Armenia','Yerevan'),
(90,'Kazakhstan','Nur-Sultan'),
(91,'Mauritania','Nouakchott'),
(92,'Kyrgyzstan','Bishkek'),
(93,'Tunisia','Tunis'),
(94,'Nepal','Kathmandu'),
(95,'Niger','Niamey'),
(96,'Nicaragua','Managua'),
(97,'Liberia','Monrovia'),
(98,'Haiti','Port-au-Prince'),
(99,'Pakistan','Islamabad'),
(100,'Canada','Ottawa'),
(101,'Sweden','Stockholm'),
(102,'Eritrea','Asmara'),
(103,'Sierra Leone','Freetown'),
(104,'Laos','Vientiane'),
(105,'Israel','Jerusalem'),
(106,'Central African Republic','Bangui'),
(107,'Panama','Panama City'),
(108,'Netherlands','Amsterdam'),
(109,'Togo','Lomé'),
(110,'Gabon','Libreville'),
(111,'Croatia','Zagreb'),
(112,'Tajikistan','Dushanbe'),
(113,'Malawi','Lilongwe'),
(114,'Benin','Cotonou'),
(115,'Sri Lanka','Colombo'),
(116,'South Africa','Pretoria'),
(117,'Norway','Oslo'),
(118,'Greece','Athens'),
(119,'Burundi','Bujumbura'),
(120,'Finland','Helsinki'),
(121,'Macedonia','Skopje'),
(122,'Moldova','Chisinau'),
(123,'Latvia','Riga'),
(124,'Jamaica','Kingston'),
(125,'Morocco','Rabat'),
(126,'Lithuania','Vilnius'),
(127,'El Salvador','San Salvador'),
(128,'Djibouti','Djibouti'),
(129,'Ireland','Dublin'),
(130,'Netherlands','The Hague'),
(131,'Paraguay','Asunción'),
(132,'Portugal','Lisbon'),
(133,'Slovakia','Bratislava'),
(134,'Estonia','Tallinn'),
(135,'Lebanon','Beirut'),
(136,'South Africa','Cape Town'),
(137,'Albania','Tirana'),
(138,'New Zealand','Wellington'),
(139,'Tanzania','Dodoma'),
(140,'Guinea-Bissau','Bissau'),
(141,'Australia','Canberra'),
(142,'South Sudan','Juba'),
(143,'Cote dIvoire','Yamoussoukro'),
(144,'Lesotho','Maseru'),
(145,'Cyprus','Nicosia'),
(146,'Namibia','Windhoek'),
(147,'Papua New Guinea','Port Moresby'),
(148,'Benin','Porto-Novo'),
(149,'Bolivia','Sucre'),
(150,'Costa Rica','San José'),
(151,'Slovenia','Ljubljana'),
(152,'Bosnia And Herzegovina','Sarajevo'),
(153,'The Bahamas','Nassau'),
(154,'South Africa','Bloemfontein'),
(155,'Martinique','Fort-de-France'),
(156,'India','New Delhi'),
(157,'Botswana','Gaborone'),
(158,'Suriname','Paramaribo'),
(159,'Timor-Leste','Dili'),
(160,'Maldives','Male'),
(161,'Guyana','Georgetown'),
(162,'Gibraltar','Gibraltar'),
(163,'Reunion','Saint-Denis'),
(164,'Equatorial Guinea','Malabo'),
(165,'Montenegro','Podgorica'),
(166,'Bahrain','Manama'),
(167,'Mauritius','Port Louis'),
(168,'Curaçao','Willemstad'),
(169,'Switzerland','Bern'),
(170,'French Polynesia','Papeete'),
(171,'Luxembourg','Luxembourg'),
(172,'Iceland','Reykjavík'),
(173,'Cabo Verde','Praia'),
(174,'Sri Lanka','Sri Jayewardenepura Kotte'),
(175,'Barbados','Bridgetown'),
(176,'Comoros','Moroni'),
(177,'Bhutan','Thimphu'),
(178,'Swaziland','Mbabane'),
(179,'New Caledonia','Nouméa'),
(180,'Solomon Islands','Honiara'),
(181,'Fiji','Suva'),
(182,'Turkey','Ankara'),
(183,'Saint Lucia','Castries'),
(184,'French Guiana','Cayenne'),
(185,'Sao Tome And Principe','São Tomé'),
(186,'Vanuatu','Port-Vila'),
(187,'Bermuda','Hamilton'),
(188,'Brunei','Bandar Seri Begawan'),
(189,'Monaco','Monaco'),
(190,'Burundi','Gitega'),
(191,'Trinidad And Tobago','Port of Spain'),
(192,'Samoa','Apia'),
(193,'Kiribati','Tarawa'),
(194,'Aruba','Oranjestad'),
(195,'Jersey','Saint Helier'),
(196,'The Gambia','Banjul'),
(197,'Mayotte','Mamoudzou'),
(198,'Marshall Islands','Majuro'),
(199,'Isle Of Man','Douglas'),
(200,'Cayman Islands','George Town'),
(201,'Seychelles','Victoria'),
(202,'Saint Vincent And The Grenadines','Kingstown'),
(203,'Andorra','Andorra la Vella'),
(204,'Antigua And Barbuda','Saint John’s'),
(205,'Tonga','Nuku‘alofa'),
(206,'Turkmenistan','Ashgabat'),
(207,'Greenland','Nuuk'),
(208,'Belize','Belmopan'),
(209,'Dominica','Roseau'),
(210,'Saint Kitts And Nevis','Basseterre'),
(211,'Faroe Islands','Tórshavn'),
(212,'American Samoa','Pago Pago'),
(213,'Malta','Valletta'),
(214,'Gaza Strip','Gaza'),
(215,'Turks And Caicos Islands','Grand Turk'),
(216,'Federated States of Micronesia','Palikir'),
(217,'Tuvalu','Funafuti'),
(218,'Liechtenstein','Vaduz'),
(219,'Swaziland','Lobamba'),
(220,'Cook Islands','Avarua'),
(221,'Grenada','Saint George’s'),
(222,'San Marino','San Marino'),
(223,'West Bank','Al Quds'),
(224,'Northern Mariana Islands','Capitol Hill'),
(225,'Falkland Islands (Islas Malvinas)','Stanley'),
(226,'Vatican City','Vatican City'),
(227,'Niue','Alofi'),
(228,'Guadeloupe','Basse-Terre'),
(229,'Guam','Hagåtña'),
(230,'Saint Martin','Marigot'),
(231,'Saint Helena, Ascension, And Tristan Da Cunha','Jamestown'),
(232,'Montserrat','Brades'),
(233,'Sint Maarten','Philipsburg'),
(234,'Nauru','Yaren'),
(235,'Kosovo','Pristina'),
(236,'Saint Barthelemy','Gustavia'),
(237,'British Virgin Islands','Road Town'),
(238,'Palau','Ngerulmud'),
(239,'Saint Pierre And Miquelon','Saint-Pierre'),
(240,'Anguilla','The Valley'),
(241,'Wallis And Futuna','Mata-Utu'),
(242,'Norfolk Island','Kingston'),
(243,'Svalbard','Longyearbyen'),
(244,'Morocco','Tifariti'),
(245,'Pitcairn Islands','Adamstown'),
(246,'Christmas Island','Flying Fish Cove'),
(247,'South Georgia And South Sandwich Islands','King Edward Point'),
(248,'Puerto Rico','San Juan'),
(249,'U.S. Virgin Islands','Charlotte Amalie');
