name: Build and Deploy

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, linux-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

#      - name: Run unit tests and give coverage
#        run: gradle test jacocoTestReport
#
#      - name: Checkstyle
#        run: gradle checkstyle

#      - name: Build jar
#        run: gradle bootJar
#
#      - name: Build and Push Docker image
#        run: |
#          export DOCKER_REGISTRY=docker.io
#          export DOCKER_USERNAME=<your-docker-username>
#          export DOCKER_PASSWORD=<your-docker-password>
#          export DOCKER_IMAGE=<your-docker-image-name>
#          gradle buildDocker
#          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#          docker tag $DOCKER_IMAGE $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE
#          docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE
